### PR TITLE
Opensource setup

### PR DESCRIPTION
**Pull request by loadingthedev**
All the changes which done in this pr

1. Added contribution guide.
2. Only npm allowed as a package manager
3. Added CODE_OF_CONDUCT for the repo.

### CODE REVIEW

**Comment by w3cj** [comment]
Thanks for doing this! Where did you find the Code of Conduct to base this on? I'd like to give credit.

**Comment by loadingthedev** [comment]
> 

https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md

**Comment by WombleWoo7547** [comment]
https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md

https://aws.github.io/code-of-conduct

**Comment by w3cj** [comment]
Closing this PR to open with my updates / changes.

**Pull request closed without merging**
