### PR TITLE
Fixes #139 - 500 ERROR

### LINKED ISSUE #139: ERROR `500` when searching for a channel
Go to the `/create` page and search for `dfgthyutrewrety5ryewretryitrye` in channel search input and you will get an error `500`.

### PR DESCRIPTION
**Pull request by babakfp**
Hi

This fixes #139 when searching for channels and receiving empty `[]` in `items`.

https://github.com/CodingGarden/listd/assets/44144724/075f188f-e306-48a4-915b-a542f4fdee0f

I have another PR that I think fixes this UI issue ☝️

### CODE REVIEW

**Comment by w3cj** [comment]
Fix linter error.

**Comment by babakfp** [comment]
This is what I don't like about pre-commit-hook. They take so long to complete and they complain about things that are not relevant to my changes!
Video:
https://drive.google.com/file/d/1nZrAVaLqc1ILOkRXHdsUvJnEn8mNholF/view?usp=sharing

**Comment by babakfp** [comment]
Also, because of a semicolon, you wasted your time, and I wasted my time. That is not a good experience.

**Comment by w3cj** [comment]
> Also, because of a semicolon, you wasted your time, and I wasted my time. That is not a good experience. Is there a system we can use so things like this can be done on github automatically?

You wasted my time by not running the linter locally on your machine. If you would have run the pre-commit hooks you would have seen this. Closing your PRs, thanks for the suggestions, but we will not accept your changes until you follow the contributing guides.

**Comment by babakfp** [comment]
I ran `lint:fix` locally and here is the commit: https://github.com/CodingGarden/listd/pull/149/commits/89db965fc7f57c4f209f831a253d6fd304f789ed
As I already explained, I ran pre-commit-hooks and they were problematic because it was giving me errors that were not relevant to my changes!

**Pull request closed without merging**
